### PR TITLE
Fixing ii_pan test to expand DRB to include DRA

### PR DESCRIPTION
**Pull request by tavinathanson**
Fixing tests to be in line with https://github.com/hammerlab/mhcnames/pull/13's expansion of DRB-only names.

### CODE REVIEW

**Review by julia326 — APPROVED** [review]

**Comment by tavinathanson** [comment]
Also added DRA1 omit to the IEDB predictor, since it didn't work otherwise.

**Review by julia326 — COMMENTED** [review]
LGTM, also up the mhctools version here?

**Comment by tavinathanson** [comment]
Done

**Comment by tavinathanson** [comment]
@julia326 this now depends on `mhcnames` `0.3.2`, which is pending: https://github.com/hammerlab/mhcnames/pull/17

**Pull request merged**
