### PR TITLE
Update to use new IEDB result format

### PR DESCRIPTION
**Pull request by timodonnell**
'rank' seems to have been renamed 'percentile_rank'

This should fix the failing travis tests

### CODE REVIEW

**Comment by iskandr** [comment]
LGTM

**Comment by timodonnell** [comment]
Weird now we're hitting a new error on Travis. Any ideas?

```
/home/travis/build/openvax/mhctools/netmhc-bundle/netMHC-4.0/Linux_x86_64/bin/netMHC [-h] [args] [fastafile/peptidefile]: Allele has too many parts: Usage: -home-travis-build-openvax-mhctools-netmhc-bundle-netMHC-4.0-Linux*x86*64-bin-netMHC [-h] [args] [fastafile-peptidefile]
2018-01-11 18:03:59,661 - mhctools.base_commandline_predictor - ERROR - Unable to determine supported alleles
Traceback (most recent call last):
  File "/home/travis/build/openvax/mhctools/mhctools/base_commandline_predictor.py", line 215, in _determine_supported_alleles
    raise ValueError("Unable to determine supported alleles")
ValueError: Unable to determine supported alleles
ok
test.test_netmhc_version.test_executable_mismatch_4_3 ... Usage: netMHC.py [options] file
netMHC.py: error: option -l: invalid integer value: 'istMHC'
2018-01-11 18:03:59,784 - mhctools.base_commandline_predictor - ERROR - netMHC-3.4 returned empty allele list
Traceback (most recent call last):
  File "/home/travis/build/openvax/mhctools/mhctools/base_commandline_predictor.py", line 201, in _determine_supported_alleles
    '%s returned empty allele list' % command
AssertionError: netMHC-3.4 returned empty allele list

**Comment by iskandr** [comment]
Huh, haven't seen that before. Does it happen if you re-run Travis?

**Comment by timodonnell** [comment]
Restarted the build

**Pull request merged**
