### PR TITLE
Add support for netMHCIIpan

### PR DESCRIPTION
**Pull request by tavinathanson**
Some highlights:
- `netMHCIIpan` expects allele names to be in a weird format, so I added some hackery that I'm not too pleased with.
- `netMHCIIpan` can expect alpha/beta alleles rather than a single allele.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/mhctools/16)

### CODE REVIEW

**Comment by iskandr** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[mhctools/alleles.py, line 80 [r1]](https://reviewable.io:443/reviews/hammerlab/mhctools/16#-JtiOkhMMzRWT4c3Szcw)** ([raw file](https://github.com/hammerlab/mhctools/blob/f8b5f1c4533a3a65f980aab368b8b4d49751bd9f/mhctools/alleles.py#L80)):</sup>
Since you're actually specifying a pair of allele pairs, maybe it's clearer to rename this to something like `ClassIIAllelePair`?  

Alternatively, why not just use tuple pairs of AlleleName objects for Class II prediction?

---

<sup>**[mhctools/alleles.py, line 133 [r1]](https://reviewable.io:443/reviews/hammerlab/mhctools/16#-JtiP0uILjo1n2a659ba)** ([raw file](https://github.com/hammerlab/mhctools/blob/f8b5f1c4533a3a65f980aab368b8b4d49751bd9f/mhctools/alleles.py#L133)):</sup>
Can you give examples of what format is acceptable for pairs of alleles?

Also, wouldn't it be easier to move the logic for pairs out alleles out of this function and have it always return AlleleNames even for class II? Otherwise, it seems like you'll have to messily handle DR genes, which usually don't specify the DRA1 allele (often assumed to be DRA1*01:01) but might give multiple DRB genes. 

---

<sup>**[mhctools/alleles.py, line 198 [r1]](https://reviewable.io:443/reviews/hammerlab/mhctools/16#-JtiPyZ-JY0Il5tBfLkT)** ([raw file](https://github.com/hammerlab/mhctools/blob/f8b5f1c4533a3a65f980aab368b8b4d49751bd9f/mhctools/alleles.py#L198)):</sup>
Can you explain the logic here? What is the allele expected to look like?

---

<sup>**[mhctools/base_predictor.py, line 32 [r1]](https://reviewable.io:443/reviews/hammerlab/mhctools/16#-JtiRw5MP6DIUmZdmhBA)** ([raw file](https://github.com/hammerlab/mhctools/blob/f8b5f1c4533a3a65f980aab368b8b4d49751bd9f/mhctools/base_predictor.py#L32)):</sup>
Add this to the parameter list with a description of what we use it for?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/mhctools/16)

**Comment by iskandr** [comment]
@tavinathanson Maybe revisit this PR this week?

**Comment by tavinathanson** [comment]
Yup, already on it

**Comment by tavinathanson** [comment]
Trumped by #29; I think I incorporated all your comments?

**Pull request closed without merging**
