### PR TITLE
added --input-fasta-file argument

### PR DESCRIPTION
**Pull request by iskandr**
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/mhctools/75)

### CODE REVIEW

**Comment by armish** [comment]
LGTM! :shipit:

**Comment by iskandr** [comment]
@julia326 @tavinathanson Locally these tests work for me but on Travis they fail in a few instances with NetMHCpan returning 0 binding predictions. Do you think that might be related to recent changes in netmhc-bundle?

**Comment by tavinathanson** [comment]
Weird, maybe related to switching the default definition of `netMHCpan` to `3.0`? @iskandr if you `git pull` the latest `bundle` from master do the tests fail locally?

**Comment by julia326** [comment]
What's weirder is that travis-ci/pr passed but travis-ci/push failed - possible that it is a local issue?

**Comment by iskandr** [comment]
@tavinathanson @julia326 Upgrading my local `netmhc-bundle` causes the same failures. 

```
test.test_known_class1_epitopes.test_MAGE_epitope(NetMHCpan(alleles=['HLA-A*01:01'], epitope_lengths=[9]), 'ESDPIVAQY') ... ERROR
test.test_known_class1_epitopes.test_MAGE_epitope(NetMHC4(alleles=['HLA-A*01:01'], epitope_lengths=[9]), 'ESDPIVAQY') ... ok
test.test_known_class1_epitopes.test_MAGE_epitope(NetMHC3(alleles=['HLA-A*01:01'], epitope_lengths=[9]), 'ESDPIVAQY') ... ok
```

Now the question is: why? What's different about netmhcpan 3.0? Why does it return 0 predictions?

```
Expected 4 epitopes from <EpitopeCollection with 0 elements>
```

**Comment by iskandr** [comment]
@tavinathanson @julia326 Using NetMHCpan from ipython gives the same result: 

```
In [7]: NetMHCpan(alleles=["A0101"]).predict({"seq":"ESDPIVAQY"})
Out[7]: <EpitopeCollection with 0 elements>
```

**Comment by iskandr** [comment]
Rebasing should fix this branch, we'll find out in a minute.

**Pull request merged**
